Alexandresolbes/SPOOKY-BNB

- app/models/user.rb
- config/routes.rb
created routes for listings, bookings and reviews
> added routes

- db/seeds.rb
j'ai cree les seed pour user et listing
> Seed user et listing

- app/controllers/listings_controller.rb
- app/models/listing.rb
- app/views/listings/index.html.erb
- app/views/listings/new.html.erb
- app/views/listings/show.html.erb
index show destroy create et new ont été créées
> create methods for lists controller

- Gemfile
- Gemfile.lock
- app/views/shared/_navbar.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
Add cloudinary and change logo banner with it
> Add cloudinary and change logo banner with it

- app/views/pages/bookings_as_guest.html.erb
- db/migrate/20220823113858_add_status_to_booking.rb
- db/migrate/20220823115537_change_status_in_bookmarks.rb
- db/schema.rb
Add column status to booking model
> Add column status to booking model

- app/views/shared/_navbar.html.erb
Change links in navbar to redirect to home page
> Change links in navbar to redirect to home page

- app/views/listings/show.html.erb
Create booking button in listing show and edit the text of edit button
> Create booking button in listing show and edit the text of edit button

- app/controllers/reviews_controller.rb
- app/views/pages/bookings_as_guest.html.erb
Fix error for the button to new review
> Fix error for the button to new review

- app/controllers/bookings_controller.rb
Fixed params issue on bookings controller
> Correct bookings

- app/models/booking.rb
- app/models/listing.rb
- app/models/user.rb
added dependant destroy to models
> added dependencies >> destroy

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/views/shared/_banner.html.erb
> Banner video

- app/javascript/application.js
Change content and speed of typed js
> Change content and speed of typed js

- Gemfile
- Gemfile.lock
- app/models/listing.rb
- config/initializers/geocoder.rb
- db/migrate/20220824084418_add_coordinates_to_listings.rb
- db/schema.rb
Geocoder addcolumn et modif du model
> Geocoder addcolumn et modif du model

- app/controllers/pages_controller.rb
- app/views/pages/bookings_as_guest.html.erb
+ reviews only available when 'past' on bookings as guest view
> bookings now automatically set as 'past'

- db/seeds.rb
Add precise addresses to seeds
> Add precise addresses to seeds

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> Navbar style

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/listings/index.html.erb
- app/views/listings/show.html.erb
> Change card style for listing

- app/views/pages/bookings_as_host.html.erb
small corrections on host buttons
> small corrections on host buttons

- app/assets/stylesheets/components/_address_autocomplete.scss
- app/assets/stylesheets/components/_index.scss
- app/views/listings/_form.html.erb
- app/views/listings/new.html.erb
> Form listing style

- app/views/listings/show.html.erb
> Listing show design updated

- app/views/pages/bookings_as_guest.html.erb
booking as guest design updated
> booking as guest design updated

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_buttons.scss
- app/javascript/application.js
- app/views/bookings/new.html.erb
- package.json
- yarn.lock
> Calendar for bookings show

- app/controllers/pages_controller.rb
- app/views/pages/profile.html.erb
- config/routes.rb
Create route, method in controller pages and view for profile user
> Create route, method in controller pages and view for profile user

- app/views/bookings/new.html.erb
- app/views/pages/profile.html.erb
- app/views/shared/_navbar.html.erb
Navbar updated for profile user link
> Navbar updated for profile user

- app/assets/stylesheets/components/_address_autocomplete.scss
- app/views/listings/_form.html.erb
- app/views/listings/new.html.erb
> Front formulaire listing ok

- app/controllers/pages_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/pages/profile.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Change navbar link and edit user form
> Change navbar link and edit user form

- app/views/listings/edit.html.erb
- app/views/listings/new.html.erb
- app/views/pages/bookings_as_host.html.erb
Modification des boutons et des formulaires tous homogènes
> Modification des boutons et des formulaires tous homogènes

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_index.scss
- app/views/devise/registrations/edit.html.erb
- app/views/listings/_form.html.erb
- app/views/listings/index.html.erb
- app/views/pages/bookings_as_guest.html.erb
- app/views/pages/bookings_as_host.html.erb
booking show and buttons colors
> booking show and buttons colors

- app/views/listings/show.html.erb
> Listing show updated

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/listings/new.html.erb
- app/views/pages/bookings_as_guest.html.erb
> Change design of forms

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/listings/_info_window.html.erb
- app/views/listings/index.html.erb
- app/views/pages/bookings_as_host.html.erb
change layout, design of bookings as host view
> change layout, design of bookings as host view

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/listings/index.html.erb
- app/views/pages/bookings_as_host.html.erb
- app/views/shared/_navbar.html.erb
Navbar changed, index cards changed, bookings host view changed
> Navbar changed, index cards changed, bookings host view changed

- db/seeds.rb
Change seeds, fix adddresses errors
> Change seeds, fix adddresses errors

- app/assets/stylesheets/components/_card.scss
- app/views/pages/bookings_as_guest.html.erb
- app/views/pages/bookings_as_host.html.erb
- app/views/reviews/_form.html.erb
Change front and buttons condition for Bookings host view and guest
> Change front and buttons condition for Bookings host view and guest

- app/views/bookings/_form.html.erb
- app/views/listings/show.html.erb
> Listing show reviews stylized

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/bookings_as_host.html.erb
- app/views/shared/_navbar.html.erb
Bookings host view enhanced and navbar links changed
> Bookings host view enhanced and navbar links changed
